CREATE TABLE finance_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id UUID NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(80) NOT NULL,
    normalized_name VARCHAR(80) NOT NULL,
    is_default BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ux_finance_categories_owner_code UNIQUE (owner_user_id, code),
    CONSTRAINT ux_finance_categories_owner_name UNIQUE (owner_user_id, normalized_name)
);

CREATE INDEX ix_finance_categories_owner
    ON finance_categories (owner_user_id, is_default DESC, name);

INSERT INTO finance_categories (
    owner_user_id,
    code,
    name,
    normalized_name,
    is_default,
    created_at,
    updated_at
)
SELECT
    owners.owner_user_id,
    defaults.code,
    defaults.name,
    defaults.normalized_name,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM (
    SELECT owner_user_id FROM incomes
    UNION
    SELECT owner_user_id FROM expenses
    UNION
    SELECT owner_user_id FROM recurring_transactions
    UNION
    SELECT owner_user_id FROM monthly_budgets
    UNION
    SELECT owner_user_id FROM financial_goals
    UNION
    SELECT owner_user_id FROM financial_goal_contributions
) owners
CROSS JOIN (
    VALUES
        ('FOOD', 'Alimentação', 'ALIMENTACAO'),
        ('TRANSPORT', 'Transporte', 'TRANSPORTE'),
        ('RENT', 'Moradia', 'MORADIA'),
        ('LEISURE', 'Lazer', 'LAZER'),
        ('HEALTH', 'Saúde', 'SAUDE'),
        ('OTHER', 'Outros', 'OUTROS')
) defaults(code, name, normalized_name);

ALTER TABLE expenses
    DROP CONSTRAINT ck_expenses_category;

ALTER TABLE expenses
    ALTER COLUMN category TYPE VARCHAR(50);

ALTER TABLE expenses
    ADD CONSTRAINT fk_expenses_category
        FOREIGN KEY (owner_user_id, category)
        REFERENCES finance_categories (owner_user_id, code)
        ON DELETE RESTRICT;

ALTER TABLE recurring_transactions
    DROP CONSTRAINT ck_recurring_transactions_category;

ALTER TABLE recurring_transactions
    ALTER COLUMN category TYPE VARCHAR(50);

ALTER TABLE recurring_transactions
    ADD CONSTRAINT fk_recurring_transactions_category
        FOREIGN KEY (owner_user_id, category)
        REFERENCES finance_categories (owner_user_id, code)
        ON DELETE RESTRICT;

ALTER TABLE monthly_budgets
    DROP CONSTRAINT ck_monthly_budgets_category;

ALTER TABLE monthly_budgets
    ALTER COLUMN category TYPE VARCHAR(50);

ALTER TABLE monthly_budgets
    ADD CONSTRAINT fk_monthly_budgets_category
        FOREIGN KEY (owner_user_id, category)
        REFERENCES finance_categories (owner_user_id, code)
        ON DELETE RESTRICT;
